name: Code Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11
  LINT_SCORE_THRESHOLD: 70 # Pylint score threshold 

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip intall pylint
      
      - name: Run pylint
        run: |
          pylint --max-line-length=120 src/ > pylint_report.txt || true 
          # Extract the pylint score
          SCORE=$(tail -n 1 pylint_report.txt | grep -oP '\d+(?=\s+total)')
          echo "Pylint score is: $SCORE"

          # Check if score is below threshold
          if [ "$SCORE" -lt "${{ env.LINT_SCORE_THRESHOLD }}" ]; then
            echo "Pylint score ($SCORE) is below the threshold of ${{ env.LINT_SCORE_THRESHOLD }}. Failing the job."
            exit 1 # Fail if the job score is too low
          fi
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip intall pytest
      
      - name: Run tests
        run: |
          pytest