name: Code Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11
  JAVA_VERSION: 11 # SonarQube requires Java
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  code-quality-analysis:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Auth to GCP
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.SA_RECOMMENDER_SYSTEM }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      
      - name: Run Tox
        run: tox -p

      - name: Upload generated coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml


  sonarqube-analysis:
    name: SonarQube Code Analysis
    needs: code-quality-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      
      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/bin/sonar-scanner
      
      - name: Get uploaded coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN